
/* Populating table ngn.hs_revenue in Production */

INSERT INTO NGN.HS_REVENUE(HS_REVENUE_PROCESS_MONTH, HS_REVENUE_LOC_GROUP_CODE, HS_REVENUE_INDEX, HS_REVENUE_CREDIT_DEBIT, HS_REVENUE_SHARE_FACTOR, HS_REVENUE_FUND, HS_REVENUE_ORGN, HS_REVENUE_ACCT, HS_REVENUE_PROG, HS_REVENUE_LEDGER_DESC, HS_REVENUE_CHANGE_USERID,HS_REVENUE_CHANGE_DATE) 
	VALUES(201707, 'FULL', 'VHSITSS', 'C', 1, '64454A', '434035', '693900', '436030', 'HS-TSC INCOME-FULL', 'TCMLV','2017-8-10 8:31:32')

INSERT INTO NGN.HS_REVENUE(HS_REVENUE_PROCESS_MONTH, HS_REVENUE_LOC_GROUP_CODE, HS_REVENUE_INDEX, HS_REVENUE_CREDIT_DEBIT, HS_REVENUE_SHARE_FACTOR, HS_REVENUE_FUND, HS_REVENUE_ORGN, HS_REVENUE_ACCT, HS_REVENUE_PROG, HS_REVENUE_LEDGER_DESC, HS_REVENUE_CHANGE_USERID,HS_REVENUE_CHANGE_DATE) 
	VALUES(201707, 'MC', 'VHSITSS', 'C', 1, '64454A', '434035', '693900', '436030', 'HS-TSC INCOME-MC', 'TCMLV','2017-8-10 8:32:32')

INSERT INTO NGN.HS_REVENUE(HS_REVENUE_PROCESS_MONTH, HS_REVENUE_LOC_GROUP_CODE, HS_REVENUE_INDEX, HS_REVENUE_CREDIT_DEBIT, HS_REVENUE_SHARE_FACTOR, HS_REVENUE_FUND, HS_REVENUE_ORGN, HS_REVENUE_ACCT, HS_REVENUE_PROG, HS_REVENUE_LEDGER_DESC, HS_REVENUE_CHANGE_USERID,HS_REVENUE_CHANGE_DATE) 
	VALUES(201707, 'OFF', 'VHSITSS', 'C', 1, '64454A', '434035', '693900', '436030', 'HS-TSC INCOME-OFF', 'TCMLV','2017-8-10 8:33:32')

INSERT INTO NGN.HS_REVENUE(HS_REVENUE_PROCESS_MONTH, HS_REVENUE_LOC_GROUP_CODE, HS_REVENUE_INDEX, HS_REVENUE_CREDIT_DEBIT, HS_REVENUE_SHARE_FACTOR, HS_REVENUE_FUND, HS_REVENUE_ORGN, HS_REVENUE_ACCT, HS_REVENUE_PROG, HS_REVENUE_LEDGER_DESC, HS_REVENUE_CHANGE_USERID,HS_REVENUE_CHANGE_DATE) 
	VALUES(201707, 'OFFHS', 'VHSITSS', 'C', 1, '64454A', '434035', '693900', '436030', 'HS-TSC INCOME-OFFHS', 'TCMLV','2017-8-10 8:33:32')


/* Populate table ngn.gl_document in Production */

select * from ngn.gl_document order by gl_calendar_year
-- use FHSTS  instead of FRITS. Per Ellen on 08/22/2017:
update ngn.gl_document set gl_hs_doc_number='FHSTS121' where GL_CALENDAR_YEAR='201706'
update ngn.gl_document set gl_hs_doc_number='FHSTS011' where GL_CALENDAR_YEAR='201707'
update ngn.gl_document set gl_hs_doc_number='FHSTS021' where GL_CALENDAR_YEAR='201708'
update ngn.gl_document set gl_hs_doc_number='FHSTS031' where GL_CALENDAR_YEAR='201709'
update ngn.gl_document set gl_hs_doc_number='FHSTS041' where GL_CALENDAR_YEAR='201710'
update ngn.gl_document set gl_hs_doc_number='FHSTS051' where GL_CALENDAR_YEAR='201711'
update ngn.gl_document set gl_hs_doc_number='FHSTS061' where GL_CALENDAR_YEAR='201712'


/* Populating ngn.hs_rate table in Production */

INSERT INTO NGN.HS_RATE(HS_RATE_PROCESS_MONTH, HS_RATE_LOC_GROUP_CODE, HS_RATE_CU_TYPE_CODE, HS_RATE_GROUP_DESC, HS_RATE_AMOUNT, HS_RATE_CHANGE_USERID, HS_RATE_CHANGE_DATE, HS_RATE_GROUP_CODE) 
SELECT NGN_RATE_PROCESS_MONTH, NGN_RATE_LOC_GROUP_CODE, NGN_RATE_CU_TYPE_CODE, NGN_RATE_GROUP_DESC, NGN_RATE_AMOUNT, NGN_RATE_CHANGE_USERID, current timestamp, NGN_RATE_GROUP_CODE
	FROM NGN.NGN_RATE where NGN_RATE_PROCESS_MONTH=201707

update ngn.hs_rate set HS_RATE_AMOUNT=108 where HS_RATE_PROCESS_MONTH=201707 and HS_RATE_LOC_GROUP_CODE in ('FULL','MC','OFFHS')
update ngn.hs_rate set HS_RATE_AMOUNT=0 where HS_RATE_PROCESS_MONTH=201707 and HS_RATE_LOC_GROUP_CODE in ('OFF')

/* populating ngn.hs_redirect based on ngn.ngn_redirect records for July 2017 */
insert into ngn.hs_redirect
select * from ngn.ngn_redirect where NGN_REDIR_PROCESS_MONTH=201707


